Repository Lams364/log-density-plugin, pull requests merged in 2024-12, with the labels that each got.

#19 fix: tabs calculation and RegexJavaResponse class definition
  docs/ollama.md
  logdensitytool/src/extension.js
  logdensitytool/src/services/factory.js
  logdensitytool/src/services/response/regexJavaResponse.js
Labels: bug

#20 Feature/fix tab and regex java response
  logdensitytool/src/extension.js
  logdensitytool/src/model_config.js
  logdensitytool/src/services/factory.js
  logdensitytool/src/services/response/JSONResponseHandler.js
  logdensitytool/src/services/response/regexJavaResponse.js
  logdensitytool/src/services/response/response.js
  logdensitytool/src/services/response/standardResponse.js
  package-lock.json
Labels: bug

#22 fix: make sure all response type returns a list
  logdensitytool/src/services/response/response.js
  logdensitytool/src/services/response/standardResponse.js
Labels: bug

#24 Feature : Prompts with txt files
  logdensitytool/package.json
  logdensitytool/src/extension.js
  logdensitytool/src/model_config.js
  logdensitytool/src/services/analyzeProject.js
  logdensitytool/src/services/apiModel/apiModel.js
  logdensitytool/src/services/apiModel/hfApiModel.js
  logdensitytool/src/services/apiModel/ollamaApiModel.js
  logdensitytool/src/services/factory.js
  logdensitytool/src/services/response/JSONResponseHandler.js
  logdensitytool/src/services/response/regexJavaResponse.js
  logdensitytool/src/services/response/response.js
  logdensitytool/src/services/response/standardResponse.js
  logdensitytool/src/utils/api.js
  logdensitytool/src/utils/modelTools.js
  prompt/generate_log.txt
Labels: enhancement

#27 final clean readme.md
  README.md
Labels: documentation

#29 remove `tbd` in readme and add demo link
  README.md
  docs/README.md
Labels: documentation

#30 Add optionnal gpu compatibility
  docs/INSTALLATION.md
  services/docker-compose.yml
Labels: bug
